version: "3.8"
services:
  api:
    build:
      context: .
    image: payme-api:latest
    container_name: payme-api
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - ./:/usr/app
    # restart: always
