version: "3.8"
services:
  redis:
    restart: always
    image: "redis:alpine"
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - ./data:/data
  chrome:
    restart: always
    image: "browserless/chrome"
    environment:
      - CONNECTION_TIMEOUT=300000
      - MAX_CONCURRENT_SESSIONS=3
      - ENABLE_CORS=true
    ports:
      - 3000:3000
  app:
    restart: always
    build:
      context: .
    ports:
      - 1338:1338
      - 9229:9229
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
      - REDIS_HOST=redis
    volumes:
      - ./:/usr/app
    command: yarn dev
